### PR TITLE
Switch out ncp for fs-extra.copy

### LINKED ISSUE #112: `ampersand` hangs after author name prompt
I made it this far:

```
» ampersand
ampersand.js - app generator

This will make a new directory for your app in:
/Users/z/Desktop

? What do you want to call the folder? ampy
? What is the human friendly title of your app? Ampy
? Do you want to use hapi or express as a server framework? hapi
? What's your name? Used to populate "author" field of "package.json", as:

{
  "name": "app",
  "version": "0.0.1",
  "author": "Your answer",
  "dependencies": ...
}

Author Name: Zeke
```

^ The process hangs here, then my fans start spinning.

```
» which node
/Users/z/.nvm/versions/io.js/v1.5.1/bin/node
```

### PR DESCRIPTION
**Pull request by fyockm**
- fix #112

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
Does the `transform` option do anything in fs-extra, i didn't think that option existed? I'd guess, without having verified this, that the various template strings are not getting replaced. 

Basically what it did before, is copy the entire folder, and do a giant {{{ variable }}} replace for anything that matches the known values in that config. That's what the transform stream does. So, maybe after the copy, you'd need to do some kind of directory stream/transform step.

**Comment by fyockm** [comment]
@HenrikJoreteg I did verify this. `fs-extra` actually uses an internal version of `ncp` for the copy, and it accepts the `transform` option. see here: https://github.com/jprichardson/node-fs-extra/blob/master/lib/copy/ncp.js

**Comment by HenrikJoreteg** [comment]
ok, cool, cool. thanks @fyockm

**Comment by kamilogorek** [comment]
Sweet! :+1:

**Comment by HenrikJoreteg** [comment]
nice :)

**Comment by fyockm** [comment]
minor bump? i feel like this is more than patch. thoughts?

**Comment by lukekarrys** [comment]
I think a patch sounds good

**Comment by fyockm** [comment]
Sold! patch it is!

published as `ampersand@3.0.6`

**Pull request merged**
