### PR TITLE
make app generation respect 'indent' if specified in config. Closes #7

### LINKED ISSUE #7: Can't set a default indent with .ampersandrc
I made a ```.ampersandrc``` file in my home dir and generated an app with ampersand.

```
{
  "indent": 2
}
```

The files generated by making an app with ```ampersand``` still have four spaces for indentation.

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
staring to try to knock off some of the older issues :) @fyockm care to review and ship if it works for you?

### CODE REVIEW

**Comment by kamilogorek** [comment]
lgtm :+1:

**Comment by fyockm** [comment]
Thanks @HenrikJoreteg! The code changes look good. I've also tested and it works well.

I think we can merge as is, but I'd like to make 1 addition before shipping:
The `.ampersandrc` example in the README shows invalid JSON. If you copy/paste this into your home directory, it doesn't work. I think we should provide a working sample, and comment on the options separately in the README. I can take care of this if you agree.

Another thought- should we provide config for setting the indentation character, space (default) or tab? This change seems to lay the groundwork to support, but that would be worthy of a separate issue/PR.

**Comment by HenrikJoreteg** [comment]
@fyockm sure, yeah. Sounds good to me. 

I think we can probably just wait to do the indentation character thing if people ask for it.

**Comment by HenrikJoreteg** [comment]
if you want to handle updating the doc per your suggestions, that'd be great. Just make the tweaks in this branch and ship when ready.

**Comment by fyockm** [comment]
@HenrikJoreteg please review the README changes. If you agree, let's :shipit:

**Pull request merged**
