### PR TITLE
Merging all prs

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
This unifying PR merges outstanding PRs into one and will make it easier to iterate through `ampersand-app` integration. 

This isn't quite ready to merge, but will serve as a working point for getting them all merged.

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
I just used it because it was already in the app. We've had some more discussions around l-dash, since they've pretty much point-by-point matched what my complaints were in that post and are wanting us to do that work.

**Comment by jdalton** [comment]
> We've had some more discussions around l-dash, since they've pretty much point-by-point matched what my complaints were in that post and are wanting to do that work for us.

:tada:!

**Comment by jdalton** [comment]
@HenrikJoreteg You [mentioned](https://twitter.com/HenrikJoreteg/status/567554121549365248) you're working on a blog post. Let me know if you have any questions or issues or anything.

**Comment by fyockm** [comment]
@HenrikJoreteg aside from the amp/lodash stuff, is there anything else holding up this mass merge of PRs?

**Comment by HenrikJoreteg** [comment]
@fyockm not really, possibly just a bit more feedback. Any thoughts on the app pattern changes @AmpersandJS/core-team ?

**Comment by latentflip** [comment]
Reviewed usage of ampersand-app and looks good to me.

**Comment by HenrikJoreteg** [comment]
major bump?

**Comment by HenrikJoreteg** [comment]
published as `3.0.0`

**Pull request merged**
